spring:
    application:
        name: asheos-api
    profiles:
        active: ${ENV:local}
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
                dialect: org.hibernate.dialect.PostgreSQLDialect

server:
    port: 8080
    servlet:
        context-path: /api

logging:
    level:
        root: INFO
        org.springframework: INFO
        br.com.gammonsistemas: DEBUG