# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Test if environment variable are set
      run: echo "ENV is $ENV"
      env:
        ENV: ${{ vars.ENV }}
        SPRING_DATASOURCE_URL: ${{ vars.DB_URL }}
        SPRING_DATASOURCE__USERNAME: ${{ vars.DB_USER }}
        SPRING_DATASOURCE__PASSWORD: ${{ vars.DB_PASSWORD }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
