# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: | 
        echo "ENV is $ENV"
        echo "DB_URL is $DB_URL"
        mvn -B package --file pom.xml
      env:
        ENV: ${{secrets.ENV}}
        DB_URL: ${{secrets.DB_URL}}
        DB_USERNAME: ${{secrets.DB_USER}}
        DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        DB_DRIVER: ${{secrets.DB_DRIVER}}
